name: eclipse_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  webview_flutter: ^4.4.1
  easy_localization: ^3.0.3
  timeago: ^3.5.0
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  flutter_screenutil: ^5.9.0
  dio: ^5.3.3
  smooth_page_indicator: ^1.1.0
  intl: ^0.18.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets\fonts\Barlow-Regular.ttf
          weight: 400
        - asset: assets\fonts\Barlow-LightItalic.ttf
        - asset: assets\fonts\Barlow-Italic.ttf
          style: italic
        - asset: assets\fonts\Barlow-Bold.ttf
          weight: 700
        - asset: assets\fonts\Barlow-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets\fonts\Barlow-SemiBold.ttf
          weight: 600

        - asset: assets\fonts\Barlow-Light.ttf
          weight: 300
          style: italic

        - asset: assets\fonts\Barlow-Medium.ttf
          weight: 500

        - asset: assets\fonts\Barlow-MediumItalic.ttf
          weight: 500
          style: italic
